[app]
    httpAddr = "localhost:8080"
    logMode = true # gorm是否打印sql语句

[session]
    name = "sessionId"
    expire = 3600 # session过期时间,秒
    path = "/"
    domain = "localhost"
    secure = false
    httpOnly = true

[blog]
    title = "Welcome to Twilight"