[app]
    httpAddr = "localhost:8080"
    pprofAddr = "localhost:6060"
    logMode = true # gorm是否打印sql语句
    env = "test" # 测试:test 线上:release

[session]
    name = "sessionId"
    expire = 3600 # session过期时间,秒
    path = "/"
    domain = "localhost"
    secure = false
    httpOnly = true

[accessSession]
    name = "accessId" # 博客对外访问session name
    expire = 3600 # session过期时间,秒
    path = "/"
    domain = "localhost"
    secure = false
    httpOnly = true

[blog]
    title = "Welcome to Twilight"

[monitor]
    dumpPath = "log/"