[[db]]
    dbType = "mysql"
    host = "192.168.198.134"
    port = 3306
    user = "root"
    password = "123456"
    dbName = "gBlog"
    dbCharset = "utf8"
    active = 20
    idle = 10
    idleTimeout ="4h"
    queryTimeout = "200ms"
    execTimeout = "300ms"
    tranTimeout = "400ms"

[[db]]
    dbType = "redis"
    host = "192.168.198.134"
    port = 6379
    password = ""
    dbNum = 0

#[[db]]
#    dbType = "mysql2"
#    host = "127.0.0.1"
#    port = 3306
#    user = "root"
#    password = "123456"
#    dbName = "gBlog"
#    dbCharset = "utf8"
#    active = 20
#    idle = 10
#    idleTimeout ="4h"
#    queryTimeout = "200ms"
#    execTimeout = "300ms"
#    tranTimeout = "400ms"